[package]
name = "mcp-attr-codegen-old"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.95"
quote = "1.0.38"
proc-macro2 = "1.0.93"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
annotate-snippets = "0.11.5"
regex = "1.11.1"
heck = "0.5.0"
